# Generated by Django 5.2.2 on 2025-06-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_academicinfo_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em andamento'), ('completed', 'Concluído'), ('denied', 'Negado')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
